// 关卡数据
const levels = [
    {
        id: 1,
        name: "交通工具",
        target: "公交车",
        size: 3,
        tiles: [
            { emoji: "🚌", correct: true, name: "公交车" },
            { emoji: "🚗", correct: false, name: "汽车" },
            { emoji: "🚲", correct: false, name: "自行车" },
            { emoji: "🚌", correct: true, name: "公交车" },
            { emoji: "🚕", correct: false, name: "出租车" },
            { emoji: "🚆", correct: false, name: "火车" },
            { emoji: "🚲", correct: false, name: "自行车" },
            { emoji: "🚌", correct: true, name: "公交车" },
            { emoji: "🚀", correct: false, name: "火箭" }
        ]
    },
    {
        id: 2,
        name: "水果",
        target: "苹果",
        size: 3,
        tiles: [
            { emoji: "🍎", correct: true, name: "苹果" },
            { emoji: "🍌", correct: false, name: "香蕉" },
            { emoji: "🍊", correct: false, name: "橙子" },
            { emoji: "🍎", correct: true, name: "苹果" },
            { emoji: "🍓", correct: false, name: "草莓" },
            { emoji: "🍐", correct: false, name: "梨" },
            { emoji: "🍎", correct: true, name: "苹果" },
            { emoji: "🍇", correct: false, name: "葡萄" },
            { emoji: "🍉", correct: false, name: "西瓜" }
        ]
    },
    {
        id: 3,
        name: "动物",
        target: "狗",
        size: 3,
        tiles: [
            { emoji: "🐶", correct: true, name: "狗" },
            { emoji: "🐱", correct: false, name: "猫" },
            { emoji: "🐭", correct: false, name: "老鼠" },
            { emoji: "🐶", correct: true, name: "狗" },
            { emoji: "🐰", correct: false, name: "兔子" },
            { emoji: "🦊", correct: false, name: "狐狸" },
            { emoji: "🐶", correct: true, name: "狗" },
            { emoji: "🐻", correct: false, name: "熊" },
            { emoji: "🐼", correct: false, name: "熊猫" }
        ]
    },
    {
        id: 4,
        name: "电子产品",
        target: "手机",
        size: 3,
        tiles: [
            { emoji: "📱", correct: true, name: "手机" },
            { emoji: "💻", correct: false, name: "笔记本电脑" },
            { emoji: "⌚", correct: false, name: "智能手表" },
            { emoji: "📱", correct: true, name: "手机" },
            { emoji: "🖥️", correct: false, name: "台式电脑" },
            { emoji: "📷", correct: false, name: "相机" },
            { emoji: "📱", correct: true, name: "手机" },
            { emoji: "🎮", correct: false, name: "游戏机" },
            { emoji: "🔦", correct: false, name: "手电筒" }
        ]
    },
    {
        id: 5,
        name: "运动项目",
        target: "足球",
        size: 3,
        tiles: [
            { emoji: "⚽", correct: true, name: "足球" },
            { emoji: "🏀", correct: false, name: "篮球" },
            { emoji: "🏈", correct: false, name: "橄榄球" },
            { emoji: "⚽", correct: true, name: "足球" },
            { emoji: "🎾", correct: false, name: "网球" },
            { emoji: "🏐", correct: false, name: "排球" },
            { emoji: "⚽", correct: true, name: "足球" },
            { emoji: "🎯", correct: false, name: "飞镖" },
            { emoji: "🏸", correct: false, name: "羽毛球" }
        ]
    },
    {
        id: 6,
        name: "天气",
        target: "太阳",
        size: 3,
        tiles: [
            { emoji: "☀️", correct: true, name: "太阳" },
            { emoji: "⛅", correct: false, name: "多云" },
            { emoji: "🌧️", correct: false, name: "雨" },
            { emoji: "☀️", correct: true, name: "太阳" },
            { emoji: "❄️", correct: false, name: "雪" },
            { emoji: "🌪️", correct: false, name: "龙卷风" },
            { emoji: "☀️", correct: true, name: "太阳" },
            { emoji: "🌩️", correct: false, name: "闪电" },
            { emoji: "🌫️", correct: false, name: "雾" }
        ]
    },
    {
        id: 7,
        name: "职业",
        target: "医生",
        size: 3,
        tiles: [
            { emoji: "👨‍⚕️", correct: true, name: "医生" },
            { emoji: "👨‍🍳", correct: false, name: "厨师" },
            { emoji: "👨‍🔬", correct: false, name: "科学家" },
            { emoji: "👨‍⚕️", correct: true, name: "医生" },
            { emoji: "👨‍🚀", correct: false, name: "宇航员" },
            { emoji: "👨‍🎨", correct: false, name: "艺术家" },
            { emoji: "👨‍⚕️", correct: true, name: "医生" },
            { emoji: "👨‍✈️", correct: false, name: "飞行员" },
            { emoji: "👨‍🔧", correct: false, name: "技工" }
        ]
    },
    {
        id: 8,
        name: "国家旗帜",
        target: "法国",
        size: 4,
        tiles: [
            { emoji: "🇫🇷", correct: true, name: "法国" },
            { emoji: "🇺🇸", correct: false, name: "美国" },
            { emoji: "🇬🇧", correct: false, name: "英国" },
            { emoji: "🇩🇪", correct: false, name: "德国" },
            { emoji: "🇫🇷", correct: true, name: "法国" },
            { emoji: "🇮🇹", correct: false, name: "意大利" },
            { emoji: "🇪🇸", correct: false, name: "西班牙" },
            { emoji: "🇨🇳", correct: false, name: "中国" },
            { emoji: "🇫🇷", correct: true, name: "法国" },
            { emoji: "🇯🇵", correct: false, name: "日本" },
            { emoji: "🇰🇷", correct: false, name: "韩国" },
            { emoji: "🇧🇷", correct: false, name: "巴西" },
            { emoji: "🇫🇷", correct: true, name: "法国" },
            { emoji: "🇨🇦", correct: false, name: "加拿大" },
            { emoji: "🇦🇺", correct: false, name: "澳大利亚" },
            { emoji: "🇮🇳", correct: false, name: "印度" }
        ]
    },
    {
        id: 9,
        name: "乐器",
        target: "吉他",
        size: 4,
        tiles: [
            { emoji: "🎸", correct: true, name: "吉他" },
            { emoji: "🎹", correct: false, name: "钢琴" },
            { emoji: "🥁", correct: false, name: "鼓" },
            { emoji: "🎺", correct: false, name: "小号" },
            { emoji: "🎸", correct: true, name: "吉他" },
            { emoji: "🎻", correct: false, name: "小提琴" },
            { emoji: "🎷", correct: false, name: "萨克斯" },
            { emoji: "🪕", correct: false, name: "班卓琴" },
            { emoji: "🎸", correct: true, name: "吉他" },
            { emoji: "🎼", correct: false, name: "乐谱" },
            { emoji: "🎤", correct: false, name: "麦克风" },
            { emoji: "🪘", correct: false, name: "康加鼓" },
            { emoji: "🎸", correct: true, name: "吉他" },
            { emoji: "🎵", correct: false, name: "音符" },
            { emoji: "🎶", correct: false, name: "多个音符" },
            { emoji: "🪗", correct: false, name: "手风琴" }
        ]
    },
    {
        id: 10,
        name: "食物",
        target: "披萨",
        size: 5,
        tiles: [
            { emoji: "🍕", correct: true, name: "披萨" },
            { emoji: "🍔", correct: false, name: "汉堡" },
            { emoji: "🌭", correct: false, name: "热狗" },
            { emoji: "🍟", correct: false, name: "薯条" },
            { emoji: "🍣", correct: false, name: "寿司" },
            { emoji: "🍕", correct: true, name: "披萨" },
            { emoji: "🥪", correct: false, name: "三明治" },
            { emoji: "🍜", correct: false, name: "面条" },
            { emoji: "🍛", correct: false, name: "咖喱饭" },
            { emoji: "🍝", correct: false, name: "意大利面" },
            { emoji: "🍕", correct: true, name: "披萨" },
            { emoji: "🥗", correct: false, name: "沙拉" },
            { emoji: "🍲", correct: false, name: "炖菜" },
            { emoji: "🍱", correct: false, name: "便当" },
            { emoji: "🍤", correct: false, name: "炸虾" },
            { emoji: "🍕", correct: true, name: "披萨" },
            { emoji: "🥘", correct: false, name: "平底锅菜" },
            { emoji: "🍙", correct: false, name: "饭团" },
            { emoji: "🍚", correct: false, name: "米饭" },
            { emoji: "🍥", correct: false, name: "鱼板" },
            { emoji: "🍕", correct: true, name: "披萨" },
            { emoji: "🥟", correct: false, name: "饺子" },
            { emoji: "🍢", correct: false, name: "关东煮" },
            { emoji: "🍡", correct: false, name: "团子" },
            { emoji: "🍧", correct: false, name: "刨冰" }
        ]
    },
    {
        id: 11,
        name: "节日",
        target: "圣诞树",
        size: 5,
        tiles: [
            { emoji: "🎄", correct: true, name: "圣诞树" },
            { emoji: "🎃", correct: false, name: "南瓜灯" },
            { emoji: "🎆", correct: false, name: "烟花" },
            { emoji: "🎇", correct: false, name: "烟花棒" },
            { emoji: "🧨", correct: false, name: "爆竹" },
            { emoji: "🎄", correct: true, name: "圣诞树" },
            { emoji: "✨", correct: false, name: "闪光" },
            { emoji: "🎉", correct: false, name: "派对" },
            { emoji: "🎊", correct: false, name: "五彩纸屑" },
            { emoji: "🎋", correct: false, name: "七夕竹" },
            { emoji: "🎄", correct: true, name: "圣诞树" },
            { emoji: "🎍", correct: false, name: "门松" },
            { emoji: "🎎", correct: false, name: "人偶" },
            { emoji: "🎏", correct: false, name: "鲤鱼旗" },
            { emoji: "🎐", correct: false, name: "风铃" },
            { emoji: "🎄", correct: true, name: "圣诞树" },
            { emoji: "🎑", correct: false, name: "赏月" },
            { emoji: "🧧", correct: false, name: "红包" },
            { emoji: "🎀", correct: false, name: "蝴蝶结" },
            { emoji: "🎁", correct: false, name: "礼物" },
            { emoji: "🎄", correct: true, name: "圣诞树" },
            { emoji: "🪔", correct: false, name: "油灯" },
            { emoji: "🎈", correct: false, name: "气球" },
            { emoji: "🎫", correct: false, name: "门票" },
            { emoji: "🪅", correct: false, name: "皮纳塔" }
        ]
    },
    {
        id: 12,
        name: "自然景观",
        target: "山",
        size: 6,
        tiles: [
            { emoji: "⛰️", correct: true, name: "山" },
            { emoji: "🌋", correct: false, name: "火山" },
            { emoji: "🏕️", correct: false, name: "露营" },
            { emoji: "🏖️", correct: false, name: "沙滩" },
            { emoji: "🏜️", correct: false, name: "沙漠" },
            { emoji: "🏝️", correct: false, name: "荒岛" },
            { emoji: "⛰️", correct: true, name: "山" },
            { emoji: "🏞️", correct: false, name: "国家公园" },
            { emoji: "🏟️", correct: false, name: "体育场" },
            { emoji: "🏛️", correct: false, name: "古典建筑" },
            { emoji: "🏗️", correct: false, name: "建筑工地" },
            { emoji: "🏘️", correct: false, name: "房屋" },
            { emoji: "⛰️", correct: true, name: "山" },
            { emoji: "🏚️", correct: false, name: "废弃房屋" },
            { emoji: "🏠", correct: false, name: "房子" },
            { emoji: "🏡", correct: false, name: "带花园的房子" },
            { emoji: "🏢", correct: false, name: "办公楼" },
            { emoji: "🏣", correct: false, name: "邮局" },
            { emoji: "⛰️", correct: true, name: "山" },
            { emoji: "🏤", correct: false, name: "欧洲邮局" },
            { emoji: "🏥", correct: false, name: "医院" },
            { emoji: "🏦", correct: false, name: "银行" },
            { emoji: "🏨", correct: false, name: "酒店" },
            { emoji: "🏩", correct: false, name: "爱情酒店" },
            { emoji: "⛰️", correct: true, name: "山" },
            { emoji: "🏪", correct: false, name: "便利店" },
            { emoji: "🏫", correct: false, name: "学校" },
            { emoji: "🏬", correct: false, name: "百货商店" },
            { emoji: "🏭", correct: false, name: "工厂" },
            { emoji: "🏯", correct: false, name: "日本城堡" },
            { emoji: "⛰️", correct: true, name: "山" },
            { emoji: "🏰", correct: false, name: "城堡" },
            { emoji: "💒", correct: false, name: "婚礼" },
            { emoji: "🗼", correct: false, name: "东京塔" },
            { emoji: "🗽", correct: false, name: "自由女神像" },
            { emoji: "⛩️", correct: false, name: "神社" }
        ]
    },
    {
        id: 13,
        name: "表情符号",
        target: "笑脸",
        size: 6,
        tiles: [
            { emoji: "😀", correct: true, name: "笑脸" },
            { emoji: "😃", correct: true, name: "笑脸" },
            { emoji: "😄", correct: false, name: "开心" },
            { emoji: "😁", correct: false, name: "咧嘴笑" },
            { emoji: "😆", correct: false, name: "笑眯眼" },
            { emoji: "😅", correct: false, name: "汗笑" },
            { emoji: "😀", correct: true, name: "笑脸" },
            { emoji: "😂", correct: false, name: "笑哭了" },
            { emoji: "🤣", correct: false, name: "笑得打滚" },
            { emoji: "😊", correct: false, name: "微笑" },
            { emoji: "😇", correct: false, name: "天使" },
            { emoji: "🙂", correct: false, name: "微微笑" },
            { emoji: "😀", correct: true, name: "笑脸" },
            { emoji: "🙃", correct: false, name: "倒脸" },
            { emoji: "😉", correct: false, name: "眨眼" },
            { emoji: "😌", correct: false, name: "放松" },
            { emoji: "😍", correct: false, name: "爱心眼" },
            { emoji: "🥰", correct: false, name: "爱心脸" },
            { emoji: "😀", correct: true, name: "笑脸" },
            { emoji: "😘", correct: false, name: "飞吻" },
            { emoji: "😗", correct: false, name: "亲吻" },
            { emoji: "😙", correct: false, name: "微笑亲吻" },
            { emoji: "😚", correct: false, name: "闭眼亲吻" },
            { emoji: "😋", correct: false, name: "美味" },
            { emoji: "😀", correct: true, name: "笑脸" },
            { emoji: "😛", correct: false, name: "吐舌" },
            { emoji: "😝", correct: false, name: "挤眼吐舌" },
            { emoji: "😜", correct: false, name: "眨眼吐舌" },
            { emoji: "🤪", correct: false, name: "疯狂" },
            { emoji: "🤨", correct: false, name: "挑眉" },
            { emoji: "😀", correct: true, name: "笑脸" },
            { emoji: "🧐", correct: false, name: "单镜片" },
            { emoji: "🤓", correct: false, name: "书呆子" },
            { emoji: "😎", correct: false, name: "酷" },
            { emoji: "🤩", correct: false, name: "星星眼" },
            { emoji: "🥳", correct: false, name: "派对" }
        ]
    },
    {
        id: 14,
        name: "饮料",
        target: "咖啡",
        size: 3,
        tiles: [
            { emoji: "☕", correct: true, name: "咖啡" },
            { emoji: "🍵", correct: false, name: "茶" },
            { emoji: "🍶", correct: false, name: "清酒" },
            { emoji: "☕", correct: true, name: "咖啡" },
            { emoji: "🍺", correct: false, name: "啤酒" },
            { emoji: "🍻", correct: false, name: "干杯" },
            { emoji: "☕", correct: true, name: "咖啡" },
            { emoji: "🥂", correct: false, name: "香槟" },
            { emoji: "🍷", correct: false, name: "红酒" }
        ]
    },
    {
        id: 15,
        name: "文具",
        target: "铅笔",
        size: 3,
        tiles: [
            { emoji: "✏️", correct: true, name: "铅笔" },
            { emoji: "📝", correct: false, name: "备忘录" },
            { emoji: "📄", correct: false, name: "纸张" },
            { emoji: "✏️", correct: true, name: "铅笔" },
            { emoji: "📎", correct: false, name: "回形针" },
            { emoji: "📏", correct: false, name: "直尺" },
            { emoji: "✏️", correct: true, name: "铅笔" },
            { emoji: "📐", correct: false, name: "三角尺" },
            { emoji: "✂️", correct: false, name: "剪刀" }
        ]
    },
    {
        id: 16,
        name: "星座",
        target: "天蝎座",
        size: 3,
        tiles: [
            { emoji: "♏", correct: true, name: "天蝎座" },
            { emoji: "♈", correct: false, name: "白羊座" },
            { emoji: "♉", correct: false, name: "金牛座" },
            { emoji: "♏", correct: true, name: "天蝎座" },
            { emoji: "♊", correct: false, name: "双子座" },
            { emoji: "♋", correct: false, name: "巨蟹座" },
            { emoji: "♏", correct: true, name: "天蝎座" },
            { emoji: "♌", correct: false, name: "狮子座" },
            { emoji: "♍", correct: false, name: "处女座" }
        ]
    },
    {
        id: 17,
        name: "天气",
        target: "降水",
        size: 3,
        tiles: [
            { emoji: "☀️", correct: false, name: "夏天" },
            { emoji: "❄️", correct: true, name: "冬天" },
            { emoji: "🍂", correct: false, name: "秋天" },
            { emoji: "☀️", correct: false, name: "夏天" },
            { emoji: "🌸", correct: false, name: "春天" },
            { emoji: "🌧️", correct: true, name: "雨季" },
            { emoji: "☀️", correct: false, name: "夏天" },
            { emoji: "🌨️", correct: true, name: "雪天" },
            { emoji: "🌪️", correct: false, name: "风暴" }
        ]
    },
    {
        id: 18,
        name: "家具",
        target: "沙发",
        size: 4,
        tiles: [
            { emoji: "🛋️", correct: true, name: "沙发" },
            { emoji: "🛏️", correct: false, name: "床" },
            { emoji: "🪑", correct: false, name: "椅子" },
            { emoji: "🚪", correct: false, name: "门" },
            { emoji: "🛋️", correct: true, name: "沙发" },
            { emoji: "🪞", correct: false, name: "镜子" },
            { emoji: "🖼️", correct: false, name: "画框" },
            { emoji: "💡", correct: false, name: "灯泡" },
            { emoji: "🛋️", correct: true, name: "沙发" },
            { emoji: "📺", correct: false, name: "电视" },
            { emoji: "🧸", correct: false, name: "泰迪熊" },
            { emoji: "🕯️", correct: false, name: "蜡烛" },
            { emoji: "🛋️", correct: true, name: "沙发" },
            { emoji: "🧹", correct: false, name: "扫帚" },
            { emoji: "🧴", correct: false, name: "乳液瓶" },
            { emoji: "🪣", correct: false, name: "桶" }
        ]
    },
    {
        id: 19,
        name: "海洋生物",
        target: "海豚",
        size: 4,
        tiles: [
            { emoji: "🐬", correct: true, name: "海豚" },
            { emoji: "🐳", correct: false, name: "鲸鱼" },
            { emoji: "🦈", correct: false, name: "鲨鱼" },
            { emoji: "🐠", correct: false, name: "热带鱼" },
            { emoji: "🐬", correct: true, name: "海豚" },
            { emoji: "🐟", correct: false, name: "鱼" },
            { emoji: "🐡", correct: false, name: "河豚" },
            { emoji: "🦀", correct: false, name: "螃蟹" },
            { emoji: "🐬", correct: true, name: "海豚" },
            { emoji: "🦞", correct: false, name: "龙虾" },
            { emoji: "🦑", correct: false, name: "乌贼" },
            { emoji: "🐙", correct: false, name: "章鱼" },
            { emoji: "🐬", correct: true, name: "海豚" },
            { emoji: "🦐", correct: false, name: "虾" },
            { emoji: "🦪", correct: false, name: "牡蛎" },
            { emoji: "🐚", correct: false, name: "海螺" }
        ]
    },
    {
        id: 20,
        name: "甜点",
        target: "蛋糕",
        size: 4,
        tiles: [
            { emoji: "🍰", correct: true, name: "蛋糕" },
            { emoji: "🧁", correct: true, name: "纸杯蛋糕" },
            { emoji: "🍮", correct: false, name: "布丁" },
            { emoji: "🍩", correct: false, name: "甜甜圈" },
            { emoji: "🍰", correct: true, name: "蛋糕" },
            { emoji: "🍪", correct: false, name: "饼干" },
            { emoji: "🎂", correct: true, name: "生日蛋糕" },
            { emoji: "🍫", correct: false, name: "巧克力" },
            { emoji: "🍰", correct: true, name: "蛋糕" },
            { emoji: "🍬", correct: false, name: "糖果" },
            { emoji: "🍭", correct: false, name: "棒棒糖" },
            { emoji: "🍯", correct: false, name: "蜂蜜罐" },
            { emoji: "🍰", correct: true, name: "蛋糕" },
            { emoji: "🍦", correct: false, name: "冰淇淋" },
            { emoji: "🍨", correct: false, name: "冰淇淋碗" },
            { emoji: "🍧", correct: false, name: "刨冰" }
        ]
    },
    {
        id: 21,
        name: "蔬菜",
        target: "胡萝卜",
        size: 5,
        tiles: [
            { emoji: "🥕", correct: true, name: "胡萝卜" },
            { emoji: "🥦", correct: false, name: "西兰花" },
            { emoji: "🥬", correct: false, name: "绿叶菜" },
            { emoji: "🥒", correct: false, name: "黄瓜" },
            { emoji: "🌶️", correct: false, name: "辣椒" },
            { emoji: "🥕", correct: true, name: "胡萝卜" },
            { emoji: "🌽", correct: false, name: "玉米" },
            { emoji: "🥔", correct: false, name: "土豆" },
            { emoji: "🍠", correct: false, name: "红薯" },
            { emoji: "🧅", correct: false, name: "洋葱" },
            { emoji: "🥕", correct: true, name: "胡萝卜" },
            { emoji: "🧄", correct: false, name: "大蒜" },
            { emoji: "🥑", correct: false, name: "牛油果" },
            { emoji: "🍆", correct: false, name: "茄子" },
            { emoji: "🍅", correct: false, name: "番茄" },
            { emoji: "🥕", correct: true, name: "胡萝卜" },
            { emoji: "🥝", correct: false, name: "猕猴桃" },
            { emoji: "🍑", correct: false, name: "桃子" },
            { emoji: "🍍", correct: false, name: "菠萝" },
            { emoji: "🥭", correct: false, name: "芒果" },
            { emoji: "🥕", correct: true, name: "胡萝卜" },
            { emoji: "🍎", correct: false, name: "苹果" },
            { emoji: "🍏", correct: false, name: "青苹果" },
            { emoji: "🍐", correct: false, name: "梨" },
            { emoji: "🍊", correct: false, name: "橙子" }
        ]
    },
    {
        id: 22,
        name: "鸟类",
        target: "鸽子",
        size: 5,
        tiles: [
            { emoji: "🕊️", correct: true, name: "鸽子" },
            { emoji: "🐦", correct: false, name: "鸟" },
            { emoji: "🐧", correct: false, name: "企鹅" },
            { emoji: "🦅", correct: false, name: "鹰" },
            { emoji: "🦉", correct: false, name: "猫头鹰" },
            { emoji: "🕊️", correct: true, name: "鸽子" },
            { emoji: "🦆", correct: false, name: "鸭子" },
            { emoji: "🦢", correct: false, name: "天鹅" },
            { emoji: "🦩", correct: false, name: "火烈鸟" },
            { emoji: "🦚", correct: false, name: "孔雀" },
            { emoji: "🕊️", correct: true, name: "鸽子" },
            { emoji: "🦜", correct: false, name: "鹦鹉" },
            { emoji: "🐓", correct: false, name: "公鸡" },
            { emoji: "🐔", correct: false, name: "鸡" },
            { emoji: "🐣", correct: false, name: "小鸡破壳" },
            { emoji: "🕊️", correct: true, name: "鸽子" },
            { emoji: "🐤", correct: false, name: "小鸡" },
            { emoji: "🐥", correct: false, name: "正面小鸡" },
            { emoji: "🦃", correct: false, name: "火鸡" },
            { emoji: "🦤", correct: false, name: "渡渡鸟" },
            { emoji: "🕊️", correct: true, name: "鸽子" },
            { emoji: "🦘", correct: false, name: "袋鼠" },
            { emoji: "🦡", correct: false, name: "獾" },
            { emoji: "🦔", correct: false, name: "刺猬" },
            { emoji: "🦝", correct: false, name: "浣熊" }
        ]
    },
    {
        id: 23,
        name: "宝石",
        target: "钻石",
        size: 5,
        tiles: [
            { emoji: "💎", correct: true, name: "钻石" },
            { emoji: "🔮", correct: false, name: "水晶球" },
            { emoji: "📿", correct: false, name: "念珠" },
            { emoji: "🧿", correct: false, name: "纳扎尔护身符" },
            { emoji: "🔱", correct: false, name: "三叉戟徽章" },
            { emoji: "💎", correct: true, name: "钻石" },
            { emoji: "⚜️", correct: false, name: "鸢尾花" },
            { emoji: "🔰", correct: false, name: "初学者标志" },
            { emoji: "♠️", correct: false, name: "黑桃" },
            { emoji: "♥️", correct: false, name: "红心" },
            { emoji: "💎", correct: true, name: "钻石" },
            { emoji: "♦️", correct: false, name: "方块" },
            { emoji: "♣️", correct: false, name: "梅花" },
            { emoji: "♟️", correct: false, name: "兵" },
            { emoji: "🃏", correct: false, name: "小丑" },
            { emoji: "💎", correct: true, name: "钻石" },
            { emoji: "🀄", correct: false, name: "红中" },
            { emoji: "🎴", correct: false, name: "花札" },
            { emoji: "🎭", correct: false, name: "表演艺术" },
            { emoji: "🖼️", correct: false, name: "画框" },
            { emoji: "💎", correct: true, name: "钻石" },
            { emoji: "🎨", correct: false, name: "调色板" },
            { emoji: "🧵", correct: false, name: "线" },
            { emoji: "🧶", correct: false, name: "毛线" },
            { emoji: "🪡", correct: false, name: "缝衣针" }
        ]
    },
    {
        id: 24,
        name: "交通工具",
        target: "飞机",
        size: 6,
        tiles: [
            { emoji: "✈️", correct: true, name: "飞机" },
            { emoji: "🚀", correct: false, name: "火箭" },
            { emoji: "🛸", correct: false, name: "飞碟" },
            { emoji: "🚁", correct: false, name: "直升机" },
            { emoji: "🛶", correct: false, name: "独木舟" },
            { emoji: "🚤", correct: false, name: "快艇" },
            { emoji: "✈️", correct: true, name: "飞机" },
            { emoji: "🛳️", correct: false, name: "客轮" },
            { emoji: "⛴️", correct: false, name: "渡轮" },
            { emoji: "🚢", correct: false, name: "轮船" },
            { emoji: "🚂", correct: false, name: "火车头" },
            { emoji: "🚃", correct: false, name: "火车车厢" },
            { emoji: "✈️", correct: true, name: "飞机" },
            { emoji: "🚄", correct: false, name: "高铁" },
            { emoji: "🚅", correct: false, name: "子弹头列车" },
            { emoji: "🚆", correct: false, name: "火车" },
            { emoji: "🚇", correct: false, name: "地铁" },
            { emoji: "🚈", correct: false, name: "轻轨" },
            { emoji: "✈️", correct: true, name: "飞机" },
            { emoji: "🚉", correct: false, name: "车站" },
            { emoji: "🚊", correct: false, name: "电车" },
            { emoji: "🚝", correct: false, name: "单轨铁路" },
            { emoji: "🚞", correct: false, name: "山区铁路" },
            { emoji: "🚋", correct: false, name: "有轨电车" },
            { emoji: "✈️", correct: true, name: "飞机" },
            { emoji: "🚌", correct: false, name: "公交车" },
            { emoji: "🚍", correct: false, name: "迎面而来的公交车" },
            { emoji: "🚎", correct: false, name: "无轨电车" },
            { emoji: "🚐", correct: false, name: "小巴" },
            { emoji: "🚑", correct: false, name: "救护车" },
            { emoji: "✈️", correct: true, name: "飞机" },
            { emoji: "🚒", correct: false, name: "消防车" },
            { emoji: "🚓", correct: false, name: "警车" },
            { emoji: "🚔", correct: false, name: "迎面而来的警车" },
            { emoji: "🚕", correct: false, name: "出租车" },
            { emoji: "🚖", correct: false, name: "迎面而来的出租车" }
        ]
    },
    {
        id: 25,
        name: "建筑",
        target: "教堂",
        size: 6,
        tiles: [
            { emoji: "⛪", correct: true, name: "教堂" },
            { emoji: "🏛️", correct: false, name: "古典建筑" },
            { emoji: "🕌", correct: false, name: "清真寺" },
            { emoji: "🕍", correct: false, name: "犹太教堂" },
            { emoji: "🛕", correct: false, name: "印度教寺庙" },
            { emoji: "🛖", correct: false, name: "小屋" },
            { emoji: "⛪", correct: true, name: "教堂" },
            { emoji: "🏘️", correct: false, name: "房屋" },
            { emoji: "🏚️", correct: false, name: "废弃房屋" },
            { emoji: "🏠", correct: false, name: "房子" },
            { emoji: "🏡", correct: false, name: "带花园的房子" },
            { emoji: "🏢", correct: false, name: "办公楼" },
            { emoji: "⛪", correct: true, name: "教堂" },
            { emoji: "🏣", correct: false, name: "邮局" },
            { emoji: "🏤", correct: false, name: "欧洲邮局" },
            { emoji: "🏥", correct: false, name: "医院" },
            { emoji: "🏦", correct: false, name: "银行" },
            { emoji: "🏨", correct: false, name: "酒店" },
            { emoji: "⛪", correct: true, name: "教堂" },
            { emoji: "🏩", correct: false, name: "爱情酒店" },
            { emoji: "🏪", correct: false, name: "便利店" },
            { emoji: "🏫", correct: false, name: "学校" },
            { emoji: "🏬", correct: false, name: "百货商店" },
            { emoji: "🏭", correct: false, name: "工厂" },
            { emoji: "⛪", correct: true, name: "教堂" },
            { emoji: "🏯", correct: false, name: "日本城堡" },
            { emoji: "🏰", correct: false, name: "城堡" },
            { emoji: "💒", correct: false, name: "婚礼" },
            { emoji: "🗼", correct: false, name: "东京塔" },
            { emoji: "🗽", correct: false, name: "自由女神像" },
            { emoji: "⛪", correct: true, name: "教堂" },
            { emoji: "⛩️", correct: false, name: "神社" },
            { emoji: "🕋", correct: false, name: "克尔白" },
            { emoji: "⛲", correct: false, name: "喷泉" },
            { emoji: "⛺", correct: false, name: "帐篷" },
            { emoji: "🌁", correct: false, name: "雾天" }
        ]
    },
    {
        id: 26,
        name: "体育用品",
        target: "篮球",
        size: 6,
        tiles: [
            { emoji: "🏀", correct: true, name: "篮球" },
            { emoji: "⚽", correct: false, name: "足球" },
            { emoji: "🏈", correct: false, name: "橄榄球" },
            { emoji: "⚾", correct: false, name: "棒球" },
            { emoji: "🥎", correct: false, name: "垒球" },
            { emoji: "🏐", correct: false, name: "排球" },
            { emoji: "🏀", correct: true, name: "篮球" },
            { emoji: "🏉", correct: false, name: "英式橄榄球" },
            { emoji: "🎾", correct: false, name: "网球" },
            { emoji: "🥏", correct: false, name: "飞盘" },
            { emoji: "🎱", correct: false, name: "台球" },
            { emoji: "🪀", correct: false, name: "悠悠球" },
            { emoji: "🏀", correct: true, name: "篮球" },
            { emoji: "🪁", correct: false, name: "风筝" },
            { emoji: "🏓", correct: false, name: "乒乓球" },
            { emoji: "🏸", correct: false, name: "羽毛球" },
            { emoji: "🏒", correct: false, name: "冰球" },
            { emoji: "🏑", correct: false, name: "曲棍球" },
            { emoji: "🏀", correct: true, name: "篮球" },
            { emoji: "🥍", correct: false, name: "长曲棍球" },
            { emoji: "🏏", correct: false, name: "板球" },
            { emoji: "🪃", correct: false, name: "回旋镖" },
            { emoji: "🎯", correct: false, name: "飞镖" },
            { emoji: "🪂", correct: false, name: "降落伞" },
            { emoji: "🏀", correct: true, name: "篮球" },
            { emoji: "🥊", correct: false, name: "拳击手套" },
            { emoji: "🥋", correct: false, name: "武术服" },
            { emoji: "🎽", correct: false, name: "跑步衫" },
            { emoji: "🛹", correct: false, name: "滑板" },
            { emoji: "🛼", correct: false, name: "轮滑鞋" },
            { emoji: "🏀", correct: true, name: "篮球" },
            { emoji: "🛷", correct: false, name: "雪橇" },
            { emoji: "⛸️", correct: false, name: "冰鞋" },
            { emoji: "🥌", correct: false, name: "冰壶石" },
            { emoji: "🎣", correct: false, name: "钓鱼竿" },
            { emoji: "🎿", correct: false, name: "滑雪" }
        ]
    },
    {
        id: 27,
        name: "颜色",
        target: "红色",
        size: 3,
        tiles: [
            { emoji: "🔴", correct: true, name: "红色" },
            { emoji: "🟠", correct: false, name: "橙色" },
            { emoji: "🟡", correct: false, name: "黄色" },
            { emoji: "🔴", correct: true, name: "红色" },
            { emoji: "🟢", correct: false, name: "绿色" },
            { emoji: "🔵", correct: false, name: "蓝色" },
            { emoji: "🔴", correct: true, name: "红色" },
            { emoji: "🟣", correct: false, name: "紫色" },
            { emoji: "🟤", correct: false, name: "棕色" }
        ]
    },
    {
        id: 28,
        name: "天气现象",
        target: "彩虹",
        size: 3,
        tiles: [
            { emoji: "🌈", correct: true, name: "彩虹" },
            { emoji: "☀️", correct: false, name: "太阳" },
            { emoji: "⛅", correct: false, name: "多云" },
            { emoji: "🌈", correct: true, name: "彩虹" },
            { emoji: "🌧️", correct: false, name: "雨" },
            { emoji: "❄️", correct: false, name: "雪" },
            { emoji: "🌈", correct: true, name: "彩虹" },
            { emoji: "🌪️", correct: false, name: "龙卷风" },
            { emoji: "🌫️", correct: false, name: "雾" }
        ]
    },
    {
        id: 29,
        name: "办公用品",
        target: "电脑",
        size: 3,
        tiles: [
            { emoji: "💻", correct: true, name: "电脑" },
            { emoji: "📱", correct: false, name: "手机" },
            { emoji: "🖨️", correct: false, name: "打印机" },
            { emoji: "💻", correct: true, name: "电脑" },
            { emoji: "🖥️", correct: true, name: "台式电脑" },
            { emoji: "⌨️", correct: false, name: "键盘" },
            { emoji: "💻", correct: true, name: "电脑" },
            { emoji: "🖱️", correct: false, name: "鼠标" },
            { emoji: "📠", correct: false, name: "传真机" }
        ]
    },
    {
        id: 30,
        name: "厨房用品",
        target: "锅",
        size: 3,
        tiles: [
            { emoji: "🍳", correct: true, name: "锅" },
            { emoji: "🍴", correct: false, name: "餐具" },
            { emoji: "🔪", correct: false, name: "刀" },
            { emoji: "🍳", correct: true, name: "锅" },
            { emoji: "🥄", correct: false, name: "勺子" },
            { emoji: "🥣", correct: false, name: "碗" },
            { emoji: "🍳", correct: true, name: "锅" },
            { emoji: "🥡", correct: false, name: "外卖盒" },
            { emoji: "🧂", correct: false, name: "盐" }
        ]
    },
    {
        id: 31,
        name: "昆虫",
        target: "蝴蝶",
        size: 4,
        tiles: [
            { emoji: "🦋", correct: true, name: "蝴蝶" },
            { emoji: "🐛", correct: false, name: "毛毛虫" },
            { emoji: "🐝", correct: false, name: "蜜蜂" },
            { emoji: "🪲", correct: false, name: "甲虫" },
            { emoji: "🦋", correct: true, name: "蝴蝶" },
            { emoji: "🐞", correct: false, name: "瓢虫" },
            { emoji: "🦗", correct: false, name: "蟋蟀" },
            { emoji: "🪳", correct: false, name: "蟑螂" },
            { emoji: "🦋", correct: true, name: "蝴蝶" },
            { emoji: "🪰", correct: false, name: "苍蝇" },
            { emoji: "🪱", correct: false, name: "蠕虫" },
            { emoji: "🦟", correct: false, name: "蚊子" },
            { emoji: "🦋", correct: true, name: "蝴蝶" },
            { emoji: "🦠", correct: false, name: "微生物" },
            { emoji: "🐜", correct: false, name: "蚂蚁" },
            { emoji: "🐌", correct: false, name: "蜗牛" }
        ]
    },
    {
        id: 32,
        name: "服装",
        target: "T恤",
        size: 4,
        tiles: [
            { emoji: "👕", correct: true, name: "T恤" },
            { emoji: "👚", correct: false, name: "女装" },
            { emoji: "👖", correct: false, name: "牛仔裤" },
            { emoji: "🧥", correct: false, name: "外套" },
            { emoji: "👕", correct: true, name: "T恤" },
            { emoji: "👔", correct: false, name: "领带" },
            { emoji: "👗", correct: false, name: "连衣裙" },
            { emoji: "👘", correct: false, name: "和服" },
            { emoji: "👕", correct: true, name: "T恤" },
            { emoji: "🥻", correct: false, name: "纱丽" },
            { emoji: "🩱", correct: false, name: "连体泳衣" },
            { emoji: "🩲", correct: false, name: "内裤" },
            { emoji: "👕", correct: true, name: "T恤" },
            { emoji: "🩳", correct: false, name: "短裤" },
            { emoji: "👙", correct: false, name: "比基尼" },
            { emoji: "👢", correct: false, name: "靴子" }
        ]
    },
    {
        id: 33,
        name: "树木",
        target: "圣诞树",
        size: 4,
        tiles: [
            { emoji: "🎄", correct: true, name: "圣诞树" },
            { emoji: "🌲", correct: false, name: "常青树" },
            { emoji: "🌳", correct: false, name: "落叶树" },
            { emoji: "🌴", correct: false, name: "棕榈树" },
            { emoji: "🎄", correct: true, name: "圣诞树" },
            { emoji: "🌵", correct: false, name: "仙人掌" },
            { emoji: "🌾", correct: false, name: "稻穗" },
            { emoji: "🌿", correct: false, name: "草药" },
            { emoji: "🎄", correct: true, name: "圣诞树" },
            { emoji: "☘️", correct: false, name: "三叶草" },
            { emoji: "🍀", correct: false, name: "四叶草" },
            { emoji: "🍁", correct: false, name: "枫叶" },
            { emoji: "🎄", correct: true, name: "圣诞树" },
            { emoji: "🍂", correct: false, name: "落叶" },
            { emoji: "🍃", correct: false, name: "树叶" },
            { emoji: "🪴", correct: false, name: "盆栽" }
        ]
    },
    {
        id: 34,
        name: "树木",
        target: "仙人掌",
        size: 4,
        tiles: [
            { emoji: "🎄", correct: false, name: "圣诞树" },
            { emoji: "🌲", correct: false, name: "常青树" },
            { emoji: "🌵", correct: true, name: "仙人掌" },
            { emoji: "🌴", correct: false, name: "棕榈树" },
            { emoji: "🎄", correct: false, name: "圣诞树" },
            { emoji: "🌵", correct: true, name: "仙人掌" },
            { emoji: "🌾", correct: false, name: "稻穗" },
            { emoji: "🌿", correct: false, name: "草药" },
            { emoji: "🎄", correct: false, name: "圣诞树" },
            { emoji: "☘️", correct: false, name: "三叶草" },
            { emoji: "🍀", correct: false, name: "四叶草" },
            { emoji: "🌵", correct: true, name: "仙人掌" },
            { emoji: "🎄", correct: false, name: "圣诞树" },
            { emoji: "🍂", correct: false, name: "落叶" },
            { emoji: "🌵", correct: true, name: "仙人掌" },
            { emoji: "🪴", correct: false, name: "盆栽" }
        ]
    },
    {
        id: 35,
        name: "天气现象",
        target: "闪电",
        size: 3,
        tiles: [
            { emoji: "⚡", correct: true, name: "闪电" },
            { emoji: "☀️", correct: false, name: "太阳" },
            { emoji: "⛅", correct: false, name: "多云" },
            { emoji: "⚡", correct: true, name: "闪电" },
            { emoji: "🌧️", correct: false, name: "雨" },
            { emoji: "❄️", correct: false, name: "雪" },
            { emoji: "⚡", correct: true, name: "闪电" },
            { emoji: "🌪️", correct: false, name: "龙卷风" },
            { emoji: "🌫️", correct: false, name: "雾" }
        ]
    },
    {
        id: 36,
        name: "电子产品",
        target: "平板电脑",
        size: 3,
        tiles: [
            { emoji: "📱", correct: false, name: "手机" },
            { emoji: "🖨️", correct: true, name: "打印机" },
            { emoji: "🖥️", correct: false, name: "台式电脑" },
            { emoji: "🖨️", correct: true, name: "打印机" },
            { emoji: "📲", correct: false, name: "手机" },
            { emoji: "🖨️", correct: true, name: "打印机" },
            { emoji: "🖱️", correct: false, name: "鼠标" },
            { emoji: "⌨️", correct: false, name: "键盘" },
            { emoji: "📷", correct: false, name: "相机" }
        ]
    },
    {
        id: 37,
        name: "厨房用具",
        target: "刀",
        size: 3,
        tiles: [
            { emoji: "🍳", correct: false, name: "平底锅" },
            { emoji: "🍲", correct: false, name: "炖锅" },
            { emoji: "🍴", correct: false, name: "餐具" },
            { emoji: "🔪", correct: true, name: "刀" },
            { emoji: "🔪", correct: true, name: "刀" },
            { emoji: "🔪", correct: true, name: "刀" },
            { emoji: "🍽️", correct: false, name: "餐盘" },
            { emoji: "🥣", correct: false, name: "碗" },
            { emoji: "🍶", correct: false, name: "瓶" }
        ]
    },
    {
        id: 38,
        name: "办公用品",
        target: "笔",
        size: 3,
        tiles: [
            { emoji: "📎", correct: false, name: "回形针" },
            { emoji: "📏", correct: false, name: "直尺" },
            { emoji: "📐", correct: false, name: "三角尺" },
            { emoji: "✏️", correct: true, name: "铅笔" },
            { emoji: "🖊️", correct: true, name: "笔" },
            { emoji: "🖋️", correct: true, name: "钢笔" },
            { emoji: "📝", correct: false, name: "备忘录" },
            { emoji: "📄", correct: false, name: "纸张" },
            { emoji: "📑", correct: false, name: "书签" }
        ]
    },
    {
        id: 39,
        name: "节日装饰",
        target: "圣诞袜",
        size: 4,
        tiles: [
            { emoji: "🎄", correct: false, name: "圣诞树" },
            { emoji: "🎅", correct: false, name: "圣诞老人" },
            { emoji: "🤶", correct: false, name: "圣诞奶奶" },
            { emoji: "🧑‍🎄", correct: false, name: "圣诞人" },
            { emoji: "🎁", correct: false, name: "礼物" },
            { emoji: "🔔", correct: false, name: "铃铛" },
            { emoji: "🎊", correct: false, name: "五彩纸屑" },
            { emoji: "🎉", correct: false, name: "派对" },
            { emoji: "🧦", correct: true, name: "圣诞袜" },
            { emoji: "🛷", correct: false, name: "雪橇" },
            { emoji: "⛄", correct: false, name: "雪人" },
            { emoji: "❄️", correct: false, name: "雪花" },
            { emoji: "✨", correct: false, name: "闪光" },
            { emoji: "🌟", correct: false, name: "星星" },
            { emoji: "💫", correct: false, name: "眩晕" },
            { emoji: "☃️", correct: false, name: "雪人" }
        ]
    },
    {
        id: 40,
        name: "健身器材",
        target: "哑铃",
        size: 4,
        tiles: [
            { emoji: "🏋️", correct: true, name: "哑铃" },
            { emoji: "🤸", correct: false, name: "侧手翻" },
            { emoji: "🤼", correct: false, name: "摔跤" },
            { emoji: "🤾", correct: false, name: "手球" },
            { emoji: "🏌️", correct: false, name: "高尔夫" },
            { emoji: "🏇", correct: false, name: "赛马" },
            { emoji: "🧘", correct: false, name: "瑜伽" },
            { emoji: "🏄", correct: false, name: "冲浪" },
            { emoji: "🏊", correct: false, name: "游泳" },
            { emoji: "🚴", correct: false, name: "自行车" },
            { emoji: "🚵", correct: false, name: "山地自行车" },
            { emoji: "🏆", correct: false, name: "奖杯" },
            { emoji: "🎽", correct: false, name: "跑步衫" },
            { emoji: "🏅", correct: false, name: "奖牌" },
            { emoji: "🥇", correct: false, name: "金牌" },
            { emoji: "🏋️‍♀️", correct: true, name: "哑铃" }
        ]
    },
    {
        id: 41,
        name: "办公设备",
        target: "投影仪",
        size: 4,
        tiles: [
            { emoji: "💻", correct: false, name: "笔记本电脑" },
            { emoji: "🖥️", correct: false, name: "台式电脑" },
            { emoji: "📱", correct: false, name: "手机" },
            { emoji: "⌚", correct: false, name: "智能手表" },
            { emoji: "🖨️", correct: false, name: "打印机" },
            { emoji: "📠", correct: false, name: "传真机" },
            { emoji: "📞", correct: false, name: "电话" },
            { emoji: "📟", correct: false, name: "寻呼机" },
            { emoji: "📺", correct: false, name: "电视" },
            { emoji: "🎥", correct: true, name: "投影仪" },
            { emoji: "📷", correct: false, name: "相机" },
            { emoji: "📹", correct: false, name: "摄像机" },
            { emoji: "🔦", correct: false, name: "手电筒" },
            { emoji: "💡", correct: false, name: "灯泡" },
            { emoji: "📡", correct: false, name: "卫星天线" },
            { emoji: "📻", correct: false, name: "收音机" }
        ]
    },
    {
        id: 42,
        name: "厨房",
        target: "饮品",
        size: 4,
        tiles: [
            { emoji: "🍳", correct: false, name: "平底锅" },
            { emoji: "🍲", correct: false, name: "炖锅" },
            { emoji: "🍴", correct: false, name: "餐具" },
            { emoji: "🔪", correct: false, name: "刀" },
            { emoji: "🧂", correct: false, name: "盐" },
            { emoji: "🥄", correct: false, name: "勺子" },
            { emoji: "🍽️", correct: false, name: "餐盘" },
            { emoji: "🥣", correct: false, name: "碗" },
            { emoji: "🍶", correct: false, name: "清水" },
            { emoji: "🧊", correct: false, name: "冰块" },
            { emoji: "🍾", correct: true, name: "香槟" },
            { emoji: "🍷", correct: true, name: "红酒" },
            { emoji: "🍸", correct: true, name: "鸡尾酒" },
            { emoji: "🍹", correct: true, name: "热带饮料" },
            { emoji: "🍺", correct: true, name: "啤酒" },
            { emoji: "🥤", correct: false, name: "空杯" }
        ]
    },
    {
        id: 43,
        name: "交通工具",
        target: "直升机",
        size: 5,
        tiles: [
            { emoji: "🚗", correct: false, name: "汽车" },
            { emoji: "🚕", correct: false, name: "出租车" },
            { emoji: "🚙", correct: false, name: "SUV" },
            { emoji: "🚌", correct: false, name: "公交车" },
            { emoji: "🚎", correct: false, name: "无轨电车" },
            { emoji: "🚐", correct: false, name: "小巴" },
            { emoji: "🚑", correct: false, name: "救护车" },
            { emoji: "🚒", correct: false, name: "消防车" },
            { emoji: "🚓", correct: false, name: "警车" },
            { emoji: "🚔", correct: false, name: "迎面而来的警车" },
            { emoji: "🚁", correct: true, name: "直升机" },
            { emoji: "🚂", correct: false, name: "火车头" },
            { emoji: "🚃", correct: false, name: "火车车厢" },
            { emoji: "🚄", correct: false, name: "高铁" },
            { emoji: "🚅", correct: false, name: "子弹头列车" },
            { emoji: "🚆", correct: false, name: "火车" },
            { emoji: "🚇", correct: false, name: "地铁" },
            { emoji: "🚈", correct: false, name: "轻轨" },
            { emoji: "🚉", correct: false, name: "车站" },
            { emoji: "🚊", correct: false, name: "电车" },
            { emoji: "🚝", correct: false, name: "单轨铁路" },
            { emoji: "🚞", correct: false, name: "山区铁路" },
            { emoji: "🚋", correct: false, name: "有轨电车" },
            { emoji: "🚠", correct: false, name: "缆车" },
            { emoji: "🚡", correct: false, name: "空中缆车" }
        ]
    },
    {
        id: 44,
        name: "电子产品",
        target: "游戏机",
        size: 5,
        tiles: [
            { emoji: "📱", correct: false, name: "手机" },
            { emoji: "💻", correct: false, name: "笔记本电脑" },
            { emoji: "🖥️", correct: false, name: "台式电脑" },
            { emoji: "⌚", correct: false, name: "智能手表" },
            { emoji: "📲", correct: false, name: "平板电脑" },
            { emoji: "🖨️", correct: false, name: "打印机" },
            { emoji: "🖱️", correct: false, name: "鼠标" },
            { emoji: "⌨️", correct: false, name: "键盘" },
            { emoji: "📷", correct: false, name: "相机" },
            { emoji: "📹", correct: false, name: "摄像机" },
            { emoji: "🎮", correct: true, name: "游戏机" },
            { emoji: "🎲", correct: false, name: "骰子" },
            { emoji: "🎯", correct: false, name: "飞镖" },
            { emoji: "🎰", correct: false, name: "老虎机" },
            { emoji: "🎳", correct: false, name: "保龄球" },
            { emoji: "🏓", correct: false, name: "乒乓球" },
            { emoji: "🏸", correct: false, name: "羽毛球" },
            { emoji: "🏒", correct: false, name: "冰球" },
            { emoji: "🏑", correct: false, name: "曲棍球" },
            { emoji: "🥍", correct: false, name: "长曲棍球" },
            { emoji: "🏏", correct: false, name: "板球" },
            { emoji: "🪃", correct: false, name: "回旋镖" },
            { emoji: "🎣", correct: false, name: "钓鱼竿" },
            { emoji: "🎽", correct: false, name: "跑步衫" },
            { emoji: "🎿", correct: false, name: "滑雪" }
        ]
    },
    {
        id: 45,
        name: "厨房",
        target: "食物",
        size: 5,
        tiles: [
            { emoji: "🍳", correct: true, name: "平底锅" },
            { emoji: "🍲", correct: true, name: "炖锅" },
            { emoji: "🍴", correct: false, name: "餐具" },
            { emoji: "🔪", correct: false, name: "刀" },
            { emoji: "🧂", correct: false, name: "盐" },
            { emoji: "🥄", correct: false, name: "勺子" },
            { emoji: "🍽️", correct: false, name: "餐盘" },
            { emoji: "🥣", correct: false, name: "碗" },
            { emoji: "🍶", correct: false, name: "空瓶" },
            { emoji: "🧊", correct: false, name: "冰块" },
            { emoji: "🍞", correct: true, name: "面包" },
            { emoji: "🥐", correct: true, name: "牛角面包" },
            { emoji: "🥖", correct: true, name: "法棍" },
            { emoji: "🥨", correct: true, name: "椒盐卷饼" },
            { emoji: "🥯", correct: true, name: "贝果" },
            { emoji: "🥞", correct: true, name: "煎饼" },
            { emoji: "🧇", correct: true, name: "华夫饼" },
            { emoji: "🧀", correct: true, name: "奶酪" },
            { emoji: "🍖", correct: true, name: "肉" },
            { emoji: "🍗", correct: true, name: "鸡腿" },
            { emoji: "🥩", correct: true, name: "牛排" },
            { emoji: "🥓", correct: true, name: "培根" },
            { emoji: "🍔", correct: true, name: "汉堡" },
            { emoji: "🍟", correct: true, name: "薯条" },
            { emoji: "🍕", correct: true, name: "批萨" }
        ]
    },
    {
        id: 46,
        name: "办公用品",
        target: "书本",
        size: 5,
        tiles: [
            { emoji: "📎", correct: false, name: "回形针" },
            { emoji: "📏", correct: false, name: "直尺" },
            { emoji: "📐", correct: false, name: "三角尺" },
            { emoji: "✏️", correct: false, name: "铅笔" },
            { emoji: "🖊️", correct: false, name: "订书机" },
            { emoji: "🖋️", correct: false, name: "钢笔" },
            { emoji: "📝", correct: false, name: "备忘录" },
            { emoji: "📄", correct: false, name: "纸张" },
            { emoji: "📑", correct: false, name: "书签" },
            { emoji: "📒", correct: true, name: "账本" },
            { emoji: "📓", correct: true, name: "笔记本" },
            { emoji: "📔", correct: true, name: "装饰笔记本" },
            { emoji: "📕", correct: true, name: "合上的书" },
            { emoji: "📖", correct: true, name: "打开的书" },
            { emoji: "📗", correct: true, name: "绿色书" },
            { emoji: "📘", correct: true, name: "蓝色书" },
            { emoji: "📙", correct: true, name: "橙色书" },
            { emoji: "📚", correct: true, name: "书籍" },
            { emoji: "📜", correct: false, name: "卷轴" },
            { emoji: "📰", correct: false, name: "报纸" },
            { emoji: "🗞️", correct: false, name: "卷起的报纸" },
            { emoji: "📱", correct: false, name: "手机" },
            { emoji: "💻", correct: false, name: "笔记本电脑" },
            { emoji: "🖥️", correct: false, name: "台式电脑" },
            { emoji: "🖨️", correct: false, name: "打印机" }
        ]
    },
    {
        id: 47,
        name: "交通工具",
        target: "火箭",
        size: 6,
        tiles: [
            { emoji: "🚗", correct: false, name: "汽车" },
            { emoji: "🚕", correct: false, name: "出租车" },
            { emoji: "🚙", correct: false, name: "SUV" },
            { emoji: "🚌", correct: false, name: "公交车" },
            { emoji: "🚎", correct: false, name: "无轨电车" },
            { emoji: "🚐", correct: false, name: "小巴" },
            { emoji: "🚑", correct: false, name: "救护车" },
            { emoji: "🚒", correct: false, name: "消防车" },
            { emoji: "🚓", correct: false, name: "警车" },
            { emoji: "🚔", correct: false, name: "迎面而来的警车" },
            { emoji: "🚁", correct: false, name: "直升机" },
            { emoji: "🚂", correct: false, name: "火车头" },
            { emoji: "🚃", correct: false, name: "火车车厢" },
            { emoji: "🚄", correct: false, name: "高铁" },
            { emoji: "🚅", correct: false, name: "子弹头列车" },
            { emoji: "🚆", correct: false, name: "火车" },
            { emoji: "🚇", correct: false, name: "地铁" },
            { emoji: "🚈", correct: false, name: "轻轨" },
            { emoji: "🚉", correct: false, name: "车站" },
            { emoji: "🚊", correct: false, name: "电车" },
            { emoji: "🚝", correct: false, name: "单轨铁路" },
            { emoji: "🚞", correct: false, name: "山区铁路" },
            { emoji: "🚋", correct: false, name: "有轨电车" },
            { emoji: "🚠", correct: false, name: "缆车" },
            { emoji: "🚡", correct: false, name: "空中缆车" },
            { emoji: "🚢", correct: false, name: "轮船" },
            { emoji: "🚤", correct: false, name: "快艇" },
            { emoji: "🛳️", correct: false, name: "客轮" },
            { emoji: "⛴️", correct: false, name: "渡轮" },
            { emoji: "🛥️", correct: false, name: "摩托艇" },
            { emoji: "🚣", correct: false, name: "划船" },
            { emoji: "🛶", correct: false, name: "独木舟" },
            { emoji: "🚁", correct: false, name: "直升机" },
            { emoji: "✈️", correct: false, name: "飞机" },
            { emoji: "🛩️", correct: false, name: "小型飞机" },
            { emoji: "🚀", correct: true, name: "火箭" }
        ]
    },
    {
        id: 48,
        name: "电子产品",
        target: "手表",
        size: 6,
        tiles: [
            { emoji: "📱", correct: false, name: "手机" },
            { emoji: "💻", correct: false, name: "笔记本电脑" },
            { emoji: "🖥️", correct: false, name: "台式电脑" },
            { emoji: "⌚", correct: true, name: "手表" },
            { emoji: "📲", correct: false, name: "平板电脑" },
            { emoji: "🖨️", correct: false, name: "打印机" },
            { emoji: "🖱️", correct: false, name: "鼠标" },
            { emoji: "⌨️", correct: false, name: "键盘" },
            { emoji: "📷", correct: false, name: "相机" },
            { emoji: "📹", correct: false, name: "摄像机" },
            { emoji: "🎮", correct: false, name: "游戏机" },
            { emoji: "🎲", correct: false, name: "骰子" },
            { emoji: "🎯", correct: false, name: "飞镖" },
            { emoji: "🎰", correct: false, name: "老虎机" },
            { emoji: "🎳", correct: false, name: "保龄球" },
            { emoji: "🏓", correct: false, name: "乒乓球" },
            { emoji: "🏸", correct: false, name: "羽毛球" },
            { emoji: "🏒", correct: false, name: "冰球" },
            { emoji: "🏑", correct: false, name: "曲棍球" },
            { emoji: "🥍", correct: false, name: "长曲棍球" },
            { emoji: "🏏", correct: false, name: "板球" },
            { emoji: "🪃", correct: false, name: "回旋镖" },
            { emoji: "🎣", correct: false, name: "钓鱼竿" },
            { emoji: "🎽", correct: false, name: "跑步衫" },
            { emoji: "🎿", correct: false, name: "滑雪" },
            { emoji: "🛷", correct: false, name: "雪橇" },
            { emoji: "🥊", correct: false, name: "拳击手套" },
            { emoji: "🥋", correct: false, name: "武术服" },
            { emoji: "🎭", correct: false, name: "表演艺术" },
            { emoji: "🖼️", correct: false, name: "画框" },
            { emoji: "🎨", correct: false, name: "调色板" },
            { emoji: "🧵", correct: false, name: "线" },
            { emoji: "🧶", correct: false, name: "毛线" },
            { emoji: "🪡", correct: false, name: "缝衣针" },
            { emoji: "🧷", correct: false, name: "安全别针" },
            { emoji: "🖍️", correct: false, name: "蜡笔" }
        ]
    },
    {
        id: 49,
        name: "厨房用品",
        target: "碗",
        size: 6,
        tiles: [
            { emoji: "🍳", correct: false, name: "平底锅" },
            { emoji: "🍲", correct: false, name: "炖锅" },
            { emoji: "🍴", correct: false, name: "餐具" },
            { emoji: "🔪", correct: false, name: "刀" },
            { emoji: "🧂", correct: false, name: "盐" },
            { emoji: "🥄", correct: false, name: "勺子" },
            { emoji: "🍽️", correct: false, name: "餐盘" },
            { emoji: "🥣", correct: true, name: "碗" },
            { emoji: "🍶", correct: false, name: "微波炉" },
            { emoji: "🧊", correct: false, name: "冰块" },
            { emoji: "🍞", correct: false, name: "面包" },
            { emoji: "🥐", correct: false, name: "牛角面包" },
            { emoji: "🥖", correct: false, name: "法棍" },
            { emoji: "🥨", correct: false, name: "椒盐卷饼" },
            { emoji: "🥯", correct: false, name: "贝果" },
            { emoji: "🥞", correct: false, name: "煎饼" },
            { emoji: "🧇", correct: false, name: "华夫饼" },
            { emoji: "🧀", correct: false, name: "奶酪" },
            { emoji: "🍖", correct: false, name: "肉" },
            { emoji: "🍗", correct: false, name: "鸡腿" },
            { emoji: "🥩", correct: false, name: "牛排" },
            { emoji: "🥓", correct: false, name: "培根" },
            { emoji: "🍔", correct: false, name: "汉堡" },
            { emoji: "🍟", correct: false, name: "薯条" },
            { emoji: "🍕", correct: false, name: "披萨" },
            { emoji: "🌭", correct: false, name: "热狗" },
            { emoji: "🥪", correct: false, name: "三明治" },
            { emoji: "🌮", correct: false, name: "玉米饼" },
            { emoji: "🌯", correct: false, name: "卷饼" },
            { emoji: "🥙", correct: false, name: "夹心饼" },
            { emoji: "🧆", correct: false, name: "炸豆丸子" },
            { emoji: "🥚", correct: false, name: "鸡蛋" },
            { emoji: "🍳", correct: false, name: "煎蛋" },
            { emoji: "🥘", correct: false, name: "平底锅菜" },
            { emoji: "🍲", correct: false, name: "炖菜" },
            { emoji: "🥣", correct: true, name: "碗" }
        ]
    },
    {
        id: 50,
        name: "办公用品",
        target: "数码",
        size: 6,
        tiles: [
            { emoji: "📎", correct: false, name: "回形针" },
            { emoji: "📏", correct: false, name: "直尺" },
            { emoji: "📐", correct: false, name: "三角尺" },
            { emoji: "✏️", correct: false, name: "铅笔" },
            { emoji: "🖊️", correct: false, name: "笔" },
            { emoji: "🖋️", correct: false, name: "笔" },
            { emoji: "📝", correct: false, name: "备忘录" },
            { emoji: "📄", correct: false, name: "纸张" },
            { emoji: "📑", correct: false, name: "书签" },
            { emoji: "📒", correct: false, name: "账本" },
            { emoji: "📓", correct: false, name: "笔记本" },
            { emoji: "📔", correct: false, name: "装饰笔记本" },
            { emoji: "📕", correct: false, name: "合上的书" },
            { emoji: "📖", correct: false, name: "打开的书" },
            { emoji: "📗", correct: false, name: "绿色书" },
            { emoji: "📘", correct: false, name: "蓝色书" },
            { emoji: "📙", correct: false, name: "橙色书" },
            { emoji: "📚", correct: false, name: "书籍" },
            { emoji: "📜", correct: false, name: "卷轴" },
            { emoji: "📰", correct: false, name: "报纸" },
            { emoji: "🗞️", correct: false, name: "卷起的报纸" },
            { emoji: "📱", correct: true, name: "手机" },
            { emoji: "💻", correct: true, name: "笔记本电脑" },
            { emoji: "🖥️", correct: true, name: "台式电脑" },
            { emoji: "🖨️", correct: true, name: "打印机" },
            { emoji: "📠", correct: true, name: "传真机" },
            { emoji: "📞", correct: true, name: "电话" },
            { emoji: "📟", correct: true, name: "寻呼机" },
            { emoji: "📺", correct: true, name: "电视" },
            { emoji: "🎥", correct: true, name: "投影仪" },
            { emoji: "📷", correct: true, name: "相机" },
            { emoji: "📹", correct: true, name: "摄像机" },
            { emoji: "🔦", correct: false, name: "手电筒" },
            { emoji: "💡", correct: false, name: "灯泡" },
            { emoji: "📡", correct: false, name: "卫星天线" },
            { emoji: "📻", correct: true, name: "收音机" }
        ]
    }
];


// 获取随机关卡
function getRandomLevel() {
    const randomIndex = Math.floor(Math.random() * levels.length);
    return levels[randomIndex];
}